# This is a basic workflow to help you get started with Actions

name: Test Server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.10
        
      - name: Setup Project
        run: |
            cd server
            poetry install
      
      - name: Code Quality
        run: poetry run black . --check
        
      - name: Pytest Testing
        env:
            GV_USERNAME: ${{ secrets.GV_USERNAME }}
            GV_PASS: ${{ secrets.GV_PASS }}
            GV_STUDENTID: ${{ secrets.GV_STUDENTID }}
        run: poetry run pytest --cov
        
      
          
